/// @description Init

// Inherit the parent event
event_inherited();

draw_set_font(global.font_16);
text = "SUPER FREAKS 1 ULTIMATE EDITION"
+ "\n"
+ "\nORIGINAL GAME 2006"
+ "\nREMASTER 2016"
+ "\nULTIMATE EDITION 2023"
+ "\nBy SuperFreaksDev/Joe Mama"
+ "\n"
+ "\nMADE WITH:"
+ "\nGame Maker Studio 2"
+ "\nMonochrome Shader from GMS2 manual"
+ "\nInput by @JujuAdams and @offalynne"
+ "\nMetronome code by JorJoe05"
+ "\nGood pixel art pretending to be bad pixel art"
+ "\nmade with Aseprite"
+ "\nThe Creation of Freaky Freak HD Painting by EngineerKappa"
+ "\n"
+ "\nCHARACTERS BY:"
+ "\nSuperFreaksDev"
+ "\nKingnormal"
+ "\n"
+ "\nMUSIC:"
+ "\nOriginal music by philRaco and SuperFreaksDev"
+ "\nbut mostly phil tbh"
+ "\nFormer placeholder music from vgmusic.com"
+ "\n"
+ "\nSOUND EFFECTS:"
+ "\nWarner Bros."
+ "\nHanna-Barbara"
+ "\nCartoon Trax"
+ "\n"
+ "\nPLAYTESTERS AND FRIENDS:"
+ "\nSuperFreaksDev (I mean I guess I count)"
+ "\nHeather Flaherty"
+ "\nKevin Doherty"
+ "\nMetalefactor"
+ "\nEngineerKappa"
+ "\nHalatnikov"
+ "\nLance Charleson"
+ "\nSpinycemb"
+ "\nAlmyriganHero"
+ "\nphilRaco"
+ "\nMotor Drive"
+ "\nJorJoe05"
+ "\nMasterDisaster64"
+ "\nPaperpuffsDev"
+ "\n"
+ "\n...uh"
+ "\nYeah I'm not sure what else to throw in here"
+ "\nThanks for Playing!"
+ "\nand more importantly..."
+ "\nSee You Next Game!"
+ "\n"
+ "\n"
+ "\nOh, right, press confirm to skip the credits"
+ "\nMusic is nice though isn't it?";
text_height = string_height_ext(text, -1, 424);
pos = 1;
my_speed = 0.075;